### DISCUSSION TITLE
FSK

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/esphome-cc1101#1] [Q&A] [answered]
continuation of https://github.com/esphome/feature-requests/issues/59#issuecomment-1093150849

@dbuezas I've been using Universal Radio Hacker and my RTL-SDR to look at the signal sent by my switch and by the CC1101. I figured out that the switch sent an FSK signal, so I read some SmartRC-CC1101 examples and added the line ELECHOUSE_cc1101.setModulation(0); to cc1101.h, which worked and made the signal match my switch more.
Here is my cc1101.yaml:
```yaml
# https://github.com/dbuezas/esphome-cc1101
esphome:
  name: cc1101
  platform: ESP32
  board: esp32dev
  includes:
    - cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

wifi:
  ssid: 
  password: 
  fast_connect: true
  power_save_mode: HIGH

logger:
api:
ota:

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        18, // SCK
        19, // MISO
        23, // MOSI
        5, // CSN
        22, // GDO0
        200, // bandwidth_in_khz
        868 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true
remote_transmitter:
  - pin: GPIO22 # This is GDO0
    carrier_duty_percent: 100%

remote_receiver:
  - pin: # This is GDO0
      number: GPIO22
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    dump:
      - raw

button:
  - platform: template
    name: Garage
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [-124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 373, -124, 124, -248, 124, -373, 124, -124, 124, -124, 248, -248, 124, -124, 124, -124, 124, -124, 248, -124, 124, -373, 124, -124, 622, -248, 622, -248, 124, -124, 373, -248, 248, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 373, -124, 124, -248, 124, -373, 124, -124, 124, -124, 248, -248, 124, -124, 124, -124, 124, -124, 248, -124, 124, -373, 124, -124, 622, -248, 622, -248, 124, -124, 373, -248, 248, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 373, -124, 124, -248, 124, -373, 124, -124, 124, -124, 248, -248, 124, -124, 124, -124, 124, -124, 248, -124, 124, -373, 124, -124, 622, -248, 622, -248, 124, -124, 373, -248, 248, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 373, -124, 124, -248, 124, -373, 124, -124, 124, -124, 248, -248, 124, -124, 124, -124, 124, -124, 248, -124, 124, -373, 124, -124, 622, -248, 622, -248, 124, -124, 373, -248, 248, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 124, -124, 373, -124, 124, -248, 124, -373, 124, -124, 124, -124, 248, -248, 124, -124, 124, -124, 124, -124, 248, -124, 124, -373, 124, -124, 622, -248, 622, -248, 124, -124, 373, -248, 248]
          repeat:
            times: 7
            wait_time: 99ms
      - lambda: get_cc1101(transciver).endTransmission();
```
It still doesn't work though, and looking at the analog signals in URH, there are two obvious differences.
I'm using repeat: in my yaml to repeat the signal. This makes the CC1101 just keep sending the "slow" signal during the wait between the repeats. See screenshot here (original on top, CC1101 on the bottom). My original switch stops sending data between the signal repeats.
![image](https://user-images.githubusercontent.com/777196/162582898-ae30d954-55cd-4e32-a912-68a953f81a18.png)

Second problem: The wavelenghts of the slow signal doesn't match, see screenshot here. Any way I can decide the wavelenghts of the different parts of the signal?
![image](https://user-images.githubusercontent.com/777196/162582933-018071fd-7133-4d6c-b99a-42e250f3961d.png)

**Comment by dbuezas** [comment, marked as answer]
## 1. Stopping the transmission between repetitions
The way this component works is by putting the cc1101 in "dumb mode" and send/receive the information through a single pin (instead of using SPI). This means that when in transmission mode, the pin can be either high or low and both states will be interpreted as "transmit one of the frequencies".
To avoid this, you'll need to turn transmission off and on again between repetitions using a [repeat-action](https://esphome.io/guides/automations.html#repeat-action)
```yaml
on_press:
  - repeat:
      count: 7
      then:
        - lambda: get_cc1101(transciver).beginTransmission();
        - remote_transmitter.transmit_raw:
            code: [........]
        - lambda: get_cc1101(transciver).endTransmission();
        - delay: 99ms
```

## 2. Picking the "slow" frequency
Warning: My understanding of FSK is very basic.
Looking at the datasheet of the cc1101 chip, it looks like this is set via the 0x15 register (DEVIATN – Modem Deviation Setting).
The ELECHOUSE_cc1101 library exposes a function to set that called [setDeviation](https://github.com/LSatan/SmartRC-CC1101-Driver-Lib/blob/master/ELECHOUSE_CC1101_SRC_DRV.cpp#L920), which takes a number between 1.586914 and 380.859375.
I didn't bother to find out what unit the parameter is in, so I recommend you to just expose that as an input in home assistant and just tweak it by trial and error.

```yaml
number:
  - platform: template
    max_value: 380.859375
    min_value: 1.586914
    step: 0.0001
    mode: slider
    optimistic: true
    unit_of_measurement: "deviations"
    name: Frequqncy Deviation
    on_value:
      then:
        - lambda: ELECHOUSE_cc1101.setDeviation(x);
```

## did it work?
I hope this does the trick, please post the screenshots of the result, I'm really curious as to how this works (and I love wiggly lines 😆)
