### DISCUSSION TITLE
Need some help to reproduce the rf signal

### DISCUSSION THREAD

**Discussion by jbrandek** [dbuezas/esphome-cc1101#15] [General]
Hi i need some help if you have some time...
i get this dump from the rf raw, i used the oscilloscope and it looks that the code repeat 6 times each, the problem is that i cannot reproduce it to make the covers motor working, any advice?

'''
[23:19:00][I][remote.raw:028]: Received Raw: -1467, 369, -724, 358, -722, 714, -353, 719, -356, 734, -343, 724, -360, 346, -719, 359, -733, 718, -362, 705, -370, 707, -376, 343, -720, 360, -726, 372, -715, 352, -720, 714, -374, 718, -363, 360, -722, 351, -713, 369, -719, 714, -344, 
[23:19:00][I][remote.raw:041]:   721, -361, 725, -348, 383, -707, 366, -724, 358, -721, 340, -733, 347, -718, 359, -732, 719, -363, 353, -722, 704, -375, 342, -720, 360, -727, 348, -733, 722, -350, 360, -730, 345, -730, 351, -719, 706 
[23:19:01][I][remote.raw:028]: Received Raw: -1496, 362, -705, 371, -708, 726, -348, 740, -345, 719, -360, 730, -344, 356, -737, 343, -721, 737, -343, 727, -356, 724, -350, 362, -706, 370, -716, 373, -693, 363, -735, 720, -337, 728, -348, 388, -710, 344, -716, 376, -719, 708, -375, 
[23:19:01][I][remote.raw:041]:   718, -363, 710, -344, 364, -734, 346, -718, 360, -732, 344, -741, 357, -694, 365, -714, 743, -340, 362, -713, 741, -337, 375, -719, 357, -708, 366, -723, 710, -367, 364, -715, 345, -716, 360, -734, 718
[23:19:01][I][remote.raw:028]: Received Raw: -1500, 340, -737, 343, -721, 710, -366, 715, -361, 726, -349, 734, -345, 367, -724, 358, -721, 715, -359, 723, -350, 710, -370, 343, -728, 354, -720, 364, -709, 368, -716, 714, -368, 716, -362, 355, -719, 363, -712, 369, -701, 733, -344, 
[23:19:01][I][remote.raw:041]:   728, -355, 719, -363, 361, -725, 350, -713, 369, -719, 360, -705, 370, -718, 371, -718, 708, -347, 367, -722, 709, -366, 365, -714, 355, -719, 365, -713, 719, -362, 363, -724, 363, -711, 369, -719, 711
[23:19:01][I][remote.raw:028]: Received Raw: -1494, 359, -725, 350, -709, 719, -362, 739, -342, 715, -361, 726, -348, 383, -709, 370, -700, 732, -344, 739, -358, 720, -340, 359, -733, 344, -740, 351, -720, 363, -712, 719, -362, 732, -345, 357, -711, 368, -722, 360, -723, 714, -359, 
[23:19:01][I][remote.raw:041]:   726, -347, 713, -370, 370, -713, 353, -719, 363, -712, 368, -725, 357, -696, 378, -713, 719, -363, 361, -724, 701, -356, 369, -716, 363, -706, 370, -716, 724, -350, 359, -733, 344, -714, 376, -718, 708
[23:19:01][I][remote.raw:028]: Received Raw: -1470, 361, -726, 363, -714, 719, -357, 708, -368, 724, -359, 721, -351, 359, -706, 370, -714, 725, -349, 714, -370, 720, -362, 353, -719, 356, -709, 367, -723, 359, -723, 700, -383, 695, -362, 363, -725, 350, -714, 369, -720, 711, -369, 
[23:19:01][I][remote.raw:041]:   721, -363, 702, -371, 363, -710, 344, -740, 351, -720, 357, -710, 369, -724, 357, -696, 740, -352, 369, -694, 737, -343, 370, -707, 375, -718, 364, -711, 717, -357, 358, -722, 364, -715, 346, -719, 736
[23:19:01][I][remote.raw:028]: Received Raw: -1469, 383, -696, 377, -701, 718, -364, 733, -344, 715, -375, 718, -338, 384, -695, 364, -715, 720, -363, 743, -339, 725, -359, 346, -718, 360, -732, 344, -716, 375, -718, 709, -348, 743, -339, 358, -720, 363, -713, 368, -724, 709, -342, 
[23:19:01][I][remote.raw:041]:   739, -359, 721, -350, 360, -728, 340, -728, 354, -719, 364, -709, 369, -718, 361, -704, 720, -361, 375, -717, 714, -354, 369, -719, 361, -701, 364, -716, 723, -350, 359, -732, 344, -715, 375, -718, 715 
[23:19:01][I][remote.raw:028]: Received Raw: -1468, 361, -723, 364, -718, 720, -350, 710, -369, 719, -361, 703, -370, 358, -711, 368, -699, 734, -343, 738, -359, 722, -350, 360, -705, 370, -714, 355, -719, 364, -710, 719, -364, 735, -343, 366, -714, 353, -719, 363, -711, 716, -363, 
[23:19:01][I][remote.raw:041]:   733, -344, 715, -348, 368, -723, 359, -699, 389, -691, 368, -724, 358, -696, 364, -734, 721, -351, 360, -703, 739, -338, 376, -718, 364, -714, 368, -695, 736, -342, 741, -336, 726, -370, 714, -355, 369
[23:19:01][I][remote.raw:028]: Received Raw: -1489, 348, -739, 345, -719, 715, -369, 719, -362, 705, -371, 707, -375, 342, -721, 360, -726, 724, -358, 721, -351, 710, -368, 364, -715, 358, -722, 340, -739, 345, -718, 735, -344, 716, -362, 355, -719, 363, -713, 369, -699, 734, -343, 
[23:19:01][I][remote.raw:041]:   740, -352, 719, -363, 360, -723, 351, -714, 368, -719, 361, -704, 372, -715, 346, -719, 735, -345, 369, -724, 709, -344, 388, -716, 343, -721, 360, -725, 725, -358, 721, -337, 714, -369, 724, -359, 346
[23:19:01][I][remote.raw:028]: Received Raw: -1462, 363, -716, 374, -694, 734, -348, 743, -334, 733, -343, 738, -359, 346, -717, 361, -735, 721, -357, 703, -370, 715, -349, 367, -722, 360, -724, 363, -716, 368, -695, 737, -343, 721, -361, 372, -717, 363, -711, 344, -729, 731, -345, 
[23:19:01][I][remote.raw:041]:   715, -375, 718, -364, 359, -695, 378, -714, 367, -715, 363, -705, 364, -717, 369, -694, 740, -343, 371, -714, 724, -350, 360, -706, 369, -730, 353, -720, 706, -376, 718, -364, 709, -344, 739, -353, 370
[23:19:01][I][remote.raw:028]: Received Raw: -1487, 362, -712, 369, -694, 736, -343, 740, -337, 727, -347, 738, -354, 368, -719, 365, -704, 719, -361, 724, -349, 735, -346, 368, -699, 383, -695, 365, -713, 370, -719, 735, -344, 716, -362, 356, -721, 362, -714, 369, -723, 710, -343, 
[23:19:01][I][remote.raw:041]:   741, -353, 719, -355, 359, -724, 365, -714, 347, -718, 365, -712, 368, -721, 360, -724, 714, -355, 369, -719, 711, -369, 344, -729, 352, -720, 364, -710, 718, -363, 712, -369, 714, -355, 720, -362, 361
[23:19:01][I][remote.raw:028]: Received Raw: -1466, 369, -700, 381, -696, 728, -354, 719, -362, 712, -369, 714, -354, 370, -720, 362, -703, 723, -360, 723, -350, 713, -370, 344, -728, 354, -720, 363, -714, 369, -714, 731, -344, 731, -352, 369, -720, 361, -703, 371, -715, 722, -350, 
[23:19:01][I][remote.raw:041]:   709, -369, 716, -362, 356, -719, 363, -713, 369, -725, 358, -697, 377, -714, 368, -720, 714, -343, 371, -706, 726, -348, 383, -707, 365, -715, 358, -722, 715, -359, 724, -350, 709, -368, 716, -363, 355
[23:19:01][I][remote.raw:028]: Received Raw: -1490, 344, -749, 341, -719, 730, -351, 717, -363, 710, -368, 716, -359, 346, -720, 361, -734, 720, -361, 702, -371, 714, -348, 366, -722, 360, -723, 364, -716, 346, -717, 741, -344, 716, -363, 356, -720, 363, -712, 368, -724, 709, -370, 
[23:19:01][I][remote.raw:041]:   714, -353, 719, -354, 359, -727, 348, -733, 347, -718, 363, -709, 370, -715, 374, -694, 734, -352, 364, -723, 709, -367, 365, -715, 346, -717, 361, -733, 720, -337, 728, -348, 734, -347, 742, -340, 360
'''

**Comment by dbuezas** [comment]
It does look like it should work.
Checklist:
* make sure transmission is working correctly (check with another receiver, double check pins, code, raw code, et
* make sure you copied the whole raw code (it spans across two log lines!)
* paste your yaml here, I can confirm that
* try to find information about the actual device. There is a chance that the real remote is actually generating a more complex signal in multiple frequencies, or modulating frequently (not only Amplitude), ...
* get an stl-sdr dongle and analyse the full spectrum of the remote (this is a bit of a rabbit hole, but a very interesting one)

Wish you luck!

**Comment by jbrandek** [comment]
I bought a broadlink to see if i resolved with it and strangely the code is almost the same just differ 2 first set of numbers...
I dont understand why the d1 with the cc1101 didnt receive those...

Broadlink converted to raw:
 code: [-7583, 4690, -1432, 366, -701, 366, -670, 731, -335, 731, -305, 731, -335, 701, -366, 335, -731, 335, -701, 701, -366, 670, -366, 701, -366, 335, -701, 366, -701, 335, -701, 366, -701, 701, -335, 731, -335, 366, -670, 366, -731, 335, -701, 701, -366, 670, -366, 701, -335, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 366, -670, 731, -335, 366, -701, 335, -731, 335, -701, 701, -366, 335, -701, 366, -701, 335, -701, 701]

Picked up by the D1 with CC1101
code: [                      -1480, 367, -711, 367, -712, 721, -362, 716, -362, 715, -363, 716, -362, 361, -711, 367, -715, 718, -362, 716, -362, 716, -362, 361, -711, 367, -710, 367, -710, 367, -711, 722, -362, 716, -362, 362, -711, 367, -710, 367, -710, 721, -363, 713, -362, 714, -361, 359, -712, 366, -709, 367, -709, 368, -712, 368, -707, 366, -710, 720, -361, 361, -710, 720, -364, 360, -712, 366, -712, 366, -710, 722, -361, 362, -710, 367, -710, 367, -710, 721]

**Reply by dbuezas** [reply]
The first ones are very long ones, probably just noise. 
Try transmitting with one and receviing with the other to ensure transmission does work.

**Reply by jbrandek** [reply]
I can make it work now but from the broadlink conversion code, with those first 2 sets of numbers i can transmit the code perfectly and it works, just dont get why in the d1 with cc1101 didnt catch those 2 numbers...

**Reply by dbuezas** [reply]
Oh wow!
The `idle` config of the remote_receiver may have a different default in the esp8266 maybe?

**Comment by jbrandek** [comment]
wow thanks, i commented the idle part and now i get the full raw code.

One question is there any way to recognize the raw code received so if i press the remote i can inform Home assistant that the blinds are moving?

**Reply by dbuezas** [reply]
of course there is! :) 
```yaml
binary_sensor:
  - platform: remote_receiver
    name: Blinds
    raw:
      code: [-7583, 4690, -1432, 366, -701, 366, -670, 731, -335, 731, -305, 731, -335, 701, -366, 335, -731, 335, -701, 701, -366, 670, -366, 701, -366, 335, -701, 366, -701, 335, -701, 366, -701, 701, -335, 731, -335, 366, -670, 366, -731, 335, -701, 701, -366, 670, -366, 701, -335, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 366, -670, 731, -335, 366, -701, 335, -731, 335, -701, 701, -366, 335, -701, 366, -701, 335, -701, 701]
```

Check out the example yaml files in this repo.

**Reply by dbuezas** [reply]
oh, you should also add a debouncing filter and whatnot.

**Reply by jbrandek** [reply]
But the raw code is always different no? It will compare the exact raw? Let me send you the copy the yaml for you to check

**Reply by dbuezas** [reply]
The raw will be slightly different, but EspHome will allow some variation so it works fine. You can even configure the % of variation allowed

**Comment by jbrandek** [comment]
```
esphome:
  name: d1-rf
  friendly_name: D1 RF
  includes:
    - cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: HIGH
  use_address: 192.168.107.231

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1-Rf Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        D5, // SCK
        D6, // MISO
        D7, // MOSI
        D3, // CSN
        D1, // GDO0
        100, // bandwidth_in_khz
        433.92 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      #id: transciver_1
      id: transciver
      name: "RSSI"
      unit_of_measurement: dBm
      entity_category: diagnostic
  # you can have multiple transcivers in the same board
  # with more than 2, an esp8266 will get out of RAM. You'll need to remove the logger and reduce the recevier buffer size to 200

remote_transmitter:
  - pin: D1 # This is GDO0
    carrier_duty_percent: 100%

remote_receiver:
  - pin: D1 # This is GDO0
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    dump:
      - raw
      #- rc_switch
    # Settings to optimize recognition of RF devices
    tolerance: 50%
    #filter: 250us
    filter: 50us
    #idle: 3ms
    #buffer_size: 2kb

button:
  - platform: template
    name: Cortina_Up
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [-7583, 4690, -1432, 366, -701, 366, -670, 731, -335, 731, -305, 731, -335, 701, -366, 335, -731, 335, -701, 701, -366, 670, -366, 701, -366, 335, -701, 366, -701, 335, -701, 366, -701, 701, -335, 731, -335, 366, -670, 366, -731, 335, -701, 701, -366, 670, -366, 701, -335, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 366, -670, 731, -335, 366, -701, 335, -731, 335, -701, 701, -366, 335, -701, 366, -701, 335, -701, 701]
          #repeat:
          #  times: 5
      - lambda: get_cc1101(transciver).endTransmission();
  - platform: template
    name: Cortina_Stop
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [-7583, 4751, -1401, 366, -701, 366, -701, 701, -366, 701, -366, 670, -366, 701, -366, 366, -670, 366, -701, 701, -335, 701, -366, 670, -366, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 731, -335, 335, -731, 335, -701, 335, -731, 701, -335, 701, -366, 701, -335, 396, -670, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 731, -305, 366, -731, 701, -335, 366, -701, 701, -335, 366, -701, 701, -366, 366, -670, 701, -366, 366, -670, 731]
          #repeat:
          #  times: 5
      - lambda: get_cc1101(transciver).endTransmission();
  - platform: template
    name: Cortina_Down
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [-7583, 4721, -1462, 335, -701, 366, -701, 701, -366, 670, -366, 701, -366, 670, -366, 366, -701, 366, -670, 731, -335, 701, -335, 731, -335, 366, -670, 366, -701, 366, -701, 335, -731, 701, -335, 701, -366, 366, -701, 366, -670, 366, -701, 670, -366, 731, -335, 701, -335, 366, -701, 366, -670, 366, -731, 335, -731, 305, -731, 335, -701, 701, -366, 366, -701, 701, -335, 366, -701, 366, -670, 731, -335, 701, -335, 366, -701, 366, -670, 731, -366, 701]
          #repeat:
          #  times: 5
      - lambda: get_cc1101(transciver).endTransmission();

cover:
- platform: time_based
  name: 'D1 RF Cover'
  id: d1_rf_cover
  device_class: blind
  assumed_state: true
  has_built_in_endstop: true

  close_action:
    - lambda: get_cc1101(transciver).beginTransmission();
    - remote_transmitter.transmit_raw:
        code: [-7583, 4721, -1462, 335, -701, 366, -701, 701, -366, 670, -366, 701, -366, 670, -366, 366, -701, 366, -670, 731, -335, 701, -335, 731, -335, 366, -670, 366, -701, 366, -701, 335, -731, 701, -335, 701, -366, 366, -701, 366, -670, 366, -701, 670, -366, 731, -335, 701, -335, 366, -701, 366, -670, 366, -731, 335, -731, 305, -731, 335, -701, 701, -366, 366, -701, 701, -335, 366, -701, 366, -670, 731, -335, 701, -335, 366, -701, 366, -670, 731, -366, 701]
        repeat:
          times: 10
    - lambda: get_cc1101(transciver).endTransmission();
  close_duration: 10s

  stop_action:
    - lambda: get_cc1101(transciver).beginTransmission();
    - remote_transmitter.transmit_raw:
        code: [-7583, 4751, -1401, 366, -701, 366, -701, 701, -366, 701, -366, 670, -366, 701, -366, 366, -670, 366, -701, 701, -335, 701, -366, 670, -366, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 731, -335, 335, -731, 335, -701, 335, -731, 701, -335, 701, -366, 701, -335, 396, -670, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 731, -305, 366, -731, 701, -335, 366, -701, 701, -335, 366, -701, 701, -366, 366, -670, 701, -366, 366, -670, 731]
        repeat:
          times: 10
    - lambda: get_cc1101(transciver).endTransmission();

  open_action:
    - lambda: get_cc1101(transciver).beginTransmission();
    - remote_transmitter.transmit_raw:
        code: [-7583, 4690, -1432, 366, -701, 366, -670, 731, -335, 731, -305, 731, -335, 701, -366, 335, -731, 335, -701, 701, -366, 670, -366, 701, -366, 335, -701, 366, -701, 335, -701, 366, -701, 701, -335, 731, -335, 366, -670, 366, -731, 335, -701, 701, -366, 670, -366, 701, -335, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 366, -670, 731, -335, 366, -701, 335, -731, 335, -701, 701, -366, 335, -701, 366, -701, 335, -701, 701]
        repeat:
          times: 10
    - lambda: get_cc1101(transciver).endTransmission();
  open_duration: 10s
```

**Reply by dbuezas** [reply]
Should work

**Comment by jbrandek** [comment]
tried this but it does not work

```
binary_sensor:
  - platform: remote_receiver
    name: "commandup"
    internal: true
    on_press:
      then:
        - cover.open: d1_rf_cover
    raw:
      code: [-7583, 4690, -1432, 366, -701, 366, -670, 731, -335, 731, -305, 731, -335, 701, -366, 335, -731, 335, -701, 701, -366, 670, -366, 701, -366, 335, -701, 366, -701, 335, -701, 366, -701, 701, -335, 731, -335, 366, -670, 366, -731, 335, -701, 701, -366, 670, -366, 701, -335, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 366, -670, 731, -335, 366, -701, 335, -731, 335, -701, 701, -366, 335, -701, 366, -701, 335, -701, 701]
  
  - platform: remote_receiver
    name: "commandstop"
    internal: true
    on_press:
      then:
        - cover.stop: d1_rf_cover
    raw:
      code: [-7583, 4751, -1401, 366, -701, 366, -701, 701, -366, 701, -366, 670, -366, 701, -366, 366, -670, 366, -701, 701, -335, 701, -366, 670, -366, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 731, -335, 335, -731, 335, -701, 335, -731, 701, -335, 701, -366, 701, -335, 396, -670, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 731, -305, 366, -731, 701, -335, 366, -701, 701, -335, 366, -701, 701, -366, 366, -670, 701, -366, 366, -670, 731]

  - platform: remote_receiver
    name: "commanddown"
    internal: true
    on_press:
      then:
        - cover.close: d1_rf_cover
    raw:
      code: [-7583, 4721, -1462, 335, -701, 366, -701, 701, -366, 670, -366, 701, -366, 670, -366, 366, -701, 366, -670, 731, -335, 701, -335, 731, -335, 366, -670, 366, -701, 366, -701, 335, -731, 701, -335, 701, -366, 366, -701, 366, -670, 366, -701, 670, -366, 731, -335, 701, -335, 366, -701, 366, -670, 366, -731, 335, -731, 305, -731, 335, -701, 701, -366, 366, -701, 701, -335, 366, -701, 366, -670, 731, -335, 701, -335, 366, -701, 366, -670, 731, -366, 701]
```

**Reply by dbuezas** [reply]
Try removing the first -7000 from the receiver.

**Reply by dbuezas** [reply]
Actually, try removing it from the transmitter too. Negative numbers just mean "dont transmit for x us"

**Reply by jbrandek** [reply]
ohh ok, let me try, so it should always start with a positive number?

btw thank you for taking the time to help me

**Reply by dbuezas** [reply]
Yes, particularly when detecting.

> btw thank you for taking the time to help me

sure thing, when I first tried to get this running I was quite mystified by it

**Comment by jbrandek** [comment]
working thanks for all  the help

just a last question is there anyway to inform home assistant without triggering the cover again?

```
binary_sensor:
  - platform: remote_receiver
    name: "commandup"
    internal: true
    on_press:
      then:
        - cover.open: d1_rf_cover
    raw:
      code: [4690, -1432, 366, -701, 366, -670, 731, -335, 731, -305, 731, -335, 701, -366, 335, -731, 335, -701, 701, -366, 670, -366, 701, -366, 335, -701, 366, -701, 335, -701, 366, -701, 701, -335, 731, -335, 366, -670, 366, -731, 335, -701, 701, -366, 670, -366, 701, -335, 366, -701, 366, -670, 366, -701, 366, -670, 366, -701, 366, -670, 731, -335, 366, -670, 731, -335, 366, -701, 335, -731, 335, -701, 701, -366, 335, -701, 366, -701, 335, -701, 701, -7583]
  ```

That is sending the raw rf again to the cover?? is there a better way to do it?
