### DISCUSSION TITLE
Strange behaviour in YAML code

### DISCUSSION THREAD

**Discussion by gavraq** [dbuezas/esphome-cc1101#19] [Q&A] [answered]
Hi,

Wondered if anyone could help understand where I am going wrong in my YAML code for the cc1101 RF transceiver.

My current setup:
Wemos D1 Mini ESP8266
cc1101 RF Tranceiver

For some reason when I try to use the exact YAML code per the CC1101.YAML in the github it gives an error right at the start of the code with the red underline under the "esphome" at the start to show that something is wrong.  I am unable to figure out exactly what it is.  Strangely, if I comment out the remote_transmitter as well as the associated buttons further below then the code is accepted and I am able to flash on to my ESP and when I press my garage keyfob it correctly receives the raw codes.

Is there something I am missing?

Here is the YAML file I am currently using which is throwing the error:

```
esphome:
  name: cc1101-8266
  friendly_name: CC1101_8266
  platform: ESP8266
  board: d1_mini
  includes:
    - cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3Nzb0mrvg+FuXrXj5ovdHv/NtZx2F++uA4F6CNGGUYU="

ota:
  password: "1ec76bb450c7fa7407d872f1be1bb2be"

wifi:
  ssid: XXX
  password: XXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cc1101-8266 Fallback Hotspot"
    password: "ta9emwH45Xm3"

captive_portal:

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        D5, // SCK
        D6, // MISO
        D7, // MOSI
        D8, // CSN
        D1, // GDO0
        200, // bandwidth_in_khz
        433.92 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true

remote_transmitter:
    - pin: D1 # This is GDO0
    carrier_duty_percent: 100%

remote_receiver:
  - pin: D1 # This is GDO0
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    dump:
      - raw
      #- rc_switch
    # Settings to optimize recognition of RF devices
    tolerance: 50%
    #filter: 250us
    filter: 50us
    #idle: 3ms
    #buffer_size: 2kb

binary_sensor:
  - platform: remote_receiver
    name: Garage Left
    raw:
      code: [366, -595, 322, -621, 337, -589, 336, -620, 321, -622, 320, -612, 336, -601, 349, -596, 343, -589, 609, -335, 622, -331, 611, -318, 340, -608, 609, -333, 316, -613, 615, -336, 608, -330, 616, -318, 338, -607, 604, -332, 342, -614, 338]
  - platform: remote_receiver
    name: Garage Right
    raw:
      code: [387, -573, 364, -562, 383, -573, 368, -569, 364, -589, 362, -579, 344, -594, 362, -564, 361, -576, 595, -343, 590, -365, 560, -382, 370, -567, 566, -370, 367, -585, 577, -346, 593, -344, 590, -361, 382, -571, 567, -369, 362, -564, 382]

button:
  - platform: template
    name: Garage Left
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [366, -595, 322, -621, 337, -589, 336, -620, 321, -622, 320, -612, 336, -601, 349, -596, 343, -589, 609, -335, 622, -331, 611, -318, 340, -608, 609, -333, 316, -613, 615, -336, 608, -330, 616, -318, 338, -607, 604, -332, 342, -614, 338]
          #repeat:
          #  times: 5
      - lambda: get_cc1101(transciver).endTransmission();
  - platform: template
    name: Garage Right
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [387, -573, 364, -562, 383, -573, 368, -569, 364, -589, 362, -579, 344, -594, 362, -564, 361, -576, 595, -343, 590, -365, 560, -382, 370, -567, 566, -370, 367, -585, 577, -346, 593, -344, 590, -361, 382, -571, 567, -369, 362, -564, 382]
          #repeat:
          #  times: 5
     - lambda: get_cc1101(transciver).endTransmission();

```
