### DISCUSSION TITLE
433Mhz - Esp32 - Reboot on transmit

### DISCUSSION THREAD

**Discussion by brunopiras** [dbuezas/esphome-cc1101#6] [General]
Hello there,

I've put on-air CC1101(433,92Mhz), after many days of hard work, finally I've switch-off my two son off rf-bridges and put all of items on esp32 rf-receiver, but now, I've tried to transmit a code for my gate door, every time I've tried the esp32 reboot itself.

this is my cc1101.h:
###############
```cpp
#ifndef CC1101TRANSCIVER_H
#define CC1101TRANSCIVER_H

#include <ELECHOUSE_CC1101_SRC_DRV.h>

int CC1101_module_count = 0;
#define get_cc1101(id) (*((CC1101 *)id))

class CC1101 : public PollingComponent, public Sensor {
  int _SCK;
  int _MISO;
  int _MOSI;
  int _CSN;
  int _GDO0;
  int _GDO2;
  float _bandwidth;
  
  float _moduleNumber;
  int _last_rssi = 0;

  void setup() {
    ELECHOUSE_cc1101.setGDO(_GDO0, _GDO2);
    ELECHOUSE_cc1101.addSpiPin(_SCK, _MISO, _MOSI, _CSN, _moduleNumber);
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.Init();
    ELECHOUSE_cc1101.setRxBW(_bandwidth);
    ELECHOUSE_cc1101.setMHZ(_freq);
    ELECHOUSE_cc1101.SetRx();
  }

 public:
  float _freq;
  CC1101(int SCK, int MISO, int MOSI, int CSN, int GDO0, int GDO2, float bandwidth,
         float freq)
      : PollingComponent(100) {
    _SCK = SCK;
    _MISO = MISO;
    _MOSI = MOSI;
    _CSN = CSN;
    _GDO0 = GDO0;
    _GDO2 = GDO2;
    _bandwidth = bandwidth;
    _freq = freq;
    _moduleNumber = CC1101_module_count++;
  }

  void beginTransmission() {
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.SetTx();
    noInterrupts();
  }
  void endTransmission() {
    interrupts();
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.setSidle(); 
  }
  void setRX() {
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.SetRx(); 
  }  
  void setBW(float bandwidth) {
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.setRxBW(bandwidth);
  }
  void setFreq(float freq) {
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.setMHZ(freq);
  }
  bool rssi_on;
  void update() override {
    int rssi = 0;
    if (rssi_on) {
      ELECHOUSE_cc1101.setModul(_moduleNumber);
      rssi = ELECHOUSE_cc1101.getRssi();
    }
    if (rssi != _last_rssi) {
      publish_state(rssi);
      _last_rssi = rssi;
    }
  }
};

#endif
```
############

yaml configuration:

```yaml
substitutions:
  name: "centralina"
  time1: 60s
esphome:
  name: ${name}
  name_add_mac_suffix: false
  on_boot:
    priority: 600.0
    then:
      if:
        condition:
          lambda: 'return id(global_3) == 1;'
        then:
          lambda: get_cc1101(transciver_1).rssi_on = true;
        else:
          lambda: get_cc1101(transciver_1).rssi_on = false;
  includes:
    - ./cc1101.h
  libraries:
    - SPI
    - SmartRC-CC1101-Driver-Lib
esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  logs:
    remote_receiver: DEBUG
    remote_transmitter: DEBUG
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: LIGHT
  ap:
    ssid: "${name} Hotspot"
    password: !secret wifi_password
api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s
ota:
  password: !secret ota_pw
  id: my_ota
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        18, // SCK
        19, // MISO
        23, // MOSI
        22, // CSN
        13, // GDO0
        14, // GDO2
        200, // bandwidth_in_khz
        433.92 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver_1
      name: "${name} RF RSSI"
      unit_of_measurement: dBm
      entity_category: diagnostic
remote_transmitter:
  - id: transmitter_1
    pin: 
      number: 14
      #inverted: True
    carrier_duty_percent: 30%   
remote_receiver:
  - id: receiver_1
    pin:
      number: 13
      inverted: True
    tolerance: 50%
    filter: 5us
    idle: 10ms
    buffer_size: 10kb   
    dump: all
switch:
#RSSI
  - platform: template
    name: "${name} RSSI"
    id: switch_rssi
    icon: mdi:skull-scan
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: diagnostic
    lambda: return get_cc1101(transciver_1).rssi_on;
    turn_on_action:
      - lambda: get_cc1101(transciver_1).rssi_on = true;
      - lambda: id(global_3) = 1;
    turn_off_action:
      - lambda: id(global_3) = 0;
      - lambda: get_cc1101(transciver_1).rssi_on = false;
number:
  - platform: template 
    name: "${name} Tempo 1(script)"
    icon: "mdi:timelapse"
    step: 10
    max_value: 180
    min_value: 30
    initial_value: 30
    restore_value: yes
    optimistic: true
    id: time_rele

  - platform: template
    max_value: 812
    min_value: 5
    step: 1
    mode: slider
    optimistic: true
    initial_value: 200
    restore_value: yes
    unit_of_measurement: "kHz"
    icon: mdi:cosine-wave
    name: BW
    on_value:
      then:
        - lambda: get_cc1101(transciver_1).setBW(x);
        - lambda: id(global_2) = x;
  - platform: template
    min_value: 378
    max_value: 464
    step: .001
    mode: box
    optimistic: true
    initial_value: 433.92
    restore_value: yes
    unit_of_measurement: "MHz"
    icon: mdi:sine-wave
    name: FREQ
    on_value:
      then:
        - lambda: get_cc1101(transciver_1).setFreq(x);
        - lambda: id(global_1) = x;

button:
  - platform: template
    name: "${name} RF Cancello"
    id: bottone_cancello
    icon: mdi:gate
    on_press:
      - lambda: get_cc1101(transciver_1).beginTransmission();
      - remote_transmitter.transmit_pronto:
          transmitter_id: transmitter_1
            data: "0000 006D 0009 0000 0007 0023 0007 0044 0006 001E 0006 006E 0006 0033 0006 0034 0006 002E 0006 0068 0006 06C3 0000 006D 0009 0000 0006 0023 0006 0064 0006 001E 0006 001F 0006 0029 0006 001F 0006 001E 0006 001F 0006 06C3 0000 006D 0009 0000 0006 0024 0006 0043 0006 001F 0006 006D 0006 0034 0006 0033 0006 002E 0007 0068 0006 06C3 0000 006D 0009 0000 0006 0024 0006 0039 0006 0048 0006 001F 0006 0029 0006 001E 0006 001F 0006 001F 0006 06C3"
      - lambda: get_cc1101(transciver_1).endTransmission();
```

Can you help me?

Thanks
