### ISSUE TITLE
Compile fails saying the pin in the lambda isn't defined

### ISSUE THREAD

**Issue by Windyo** [dbuezas/esphome-cc1101#11]
I might just not be great at this, sorry.

<details>
<summary>Steps Followed</summary>

- downloaded https://github.com/dbuezas/esphome-cc1101/blob/main/cc1101.h
- put it in the /config/esphome/
- added ESP32 board to ESPHome
- added content from YAML to config file
- renamed elements as we're not using the same board.
</details>

<details>
<summary>YAML</summary>

```
esphome:
  name: esphome-web-dde34c
  friendly_name: ESPHome - Faro Radio
  includes:
    - cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Dde34C"
    password: "muD8LhuLQ3Qp"

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        GPIO18, // SCK
        GPIO19, // MISO
        GPIO23, // MOSI
        GPIO5, // CSN
        GPIO13, // GDO0
        200, // bandwidth_in_khz
        303.875 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true
    
remote_transmitter:
  - pin: GPIO13 # This is GDO0
    carrier_duty_percent: 100%

remote_receiver:
  - pin: GPIO13 # This is GDO0
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    dump:
      - raw
binary_sensor:
  - platform: remote_receiver
    name: Garage
    raw:
      code: [415,-300,370,-300,375,-300,378,-300,378,-300,379,-300,405]
button:
  - platform: template
    name: Garage
    on_press:
      - lambda: get_cc1101(transciver).beginTransmission();
      - remote_transmitter.transmit_raw:
          code: [415,-300,370,-300,375,-300,378,-300,378,-300,379,-300,405]
      - lambda: get_cc1101(transciver).endTransmission();
```
</details>

I can't get the file to compile, it fails after a minute or so complaining for example "error: 'GPIO18' was not declared in this scope".

Any help appreciated.

<details>
<summary>Error Log</summary>

```
/config/esphome/esphome-web-dde34c.yaml: In lambda function:
/config/esphome/esphome-web-dde34c.yaml:39:9: error: 'GPIO18' was not declared in this scope
         GPIO18, // SCK
         ^~~~~~
/config/esphome/esphome-web-dde34c.yaml:39:9: note: suggested alternative: 'GPIO'
         GPIO18, // SCK
         ^~~~~~
         GPIO
/config/esphome/esphome-web-dde34c.yaml:40:9: error: 'GPIO19' was not declared in this scope
         GPIO19, // MISO
         ^~~~~~
/config/esphome/esphome-web-dde34c.yaml:40:9: note: suggested alternative: 'GPIO'
         GPIO19, // MISO
         ^~~~~~
         GPIO
/config/esphome/esphome-web-dde34c.yaml:41:9: error: 'GPIO23' was not declared in this scope
         GPIO23, // MOSI
         ^~~~~~
/config/esphome/esphome-web-dde34c.yaml:41:9: note: suggested alternative: 'GPIO'
         GPIO23, // MOSI
         ^~~~~~
         GPIO
/config/esphome/esphome-web-dde34c.yaml:42:9: error: 'GPIO5' was not declared in this scope
         GPIO5, // CSN
         ^~~~~
/config/esphome/esphome-web-dde34c.yaml:42:9: note: suggested alternative: 'GPIO'
         GPIO5, // CSN
         ^~~~~
         GPIO
/config/esphome/esphome-web-dde34c.yaml:43:9: error: 'GPIO13' was not declared in this scope
         GPIO13, // GDO0
         ^~~~~~
/config/esphome/esphome-web-dde34c.yaml:43:9: note: suggested alternative: 'GPIO'
         GPIO13, // GDO0
         ^~~~~~
         GPIO
/config/esphome/esphome-web-dde34c.yaml:48:24: error: could not convert '{my_sensor}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
       return {my_sensor};
                        ^
*** [/data/esphome-web-dde34c/.pioenvs/esphome-web-dde34c/src/main.cpp.o] Error 1
========================= [FAILED] Took 532.71 seconds =========================
```

</details>
