### ISSUE TITLE
LILYGO T-Embed CC1101 Support

### ISSUE THREAD

**Issue by the-mentor** [dbuezas/esphome-cc1101#31]
Hi I'm trying to get this working on a LILYGO T-Embed CC1101 and having some trouble getting it to work 

[Board Pinout](https://cdn.shopify.com/s/files/1/0617/7190/7253/files/T-Embed-CC1101.jpg?v=1727319934)

I'm not sure what is GDO0 on this board 

i used this code as the board in ESPHome 
```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
```
This is the sensor code (I tried different pins for GDO0 37,38,47,48)

```
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        // esp32 example
        11, // SCK
        10, // MISO
        9, // MOSI
        12, // CSN
        47, // GDO0

        200, // bandwidth_in_khz
        433.92, // freq_in_mhz
        id(transmitter) // id of remote_transmitter
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true
```

this is my receiver and transmitter code 

```
remote_transmitter:   
  - id: transmitter
    rmt_channel: 0
    pin:
      number: 47 # This is GDO0
      allow_other_uses: true
    carrier_duty_percent: 100%

remote_receiver:
  - id: receiver
    rmt_channel: 5
    pin:
      number: 47 # This is GDO0
      allow_other_uses: true
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    dump:
      - raw
```

I had to add the rmt_channel because of the ESP32-S3 board requires it.

Thanks in advance !!
- DM
