### ISSUE TITLE
ESPHOME: Custom Components are deprecated

### ISSUE THREAD

**Issue by ibratos** [dbuezas/esphome-cc1101#33]
Will the CC1101 integration in esphome be published as an external component?

Warning
[Custom Components are deprecated](https://esphome.io/guides/contributing#a-note-about-custom-components), not recommended for new configurations and will be removed from ESPHome in the 2025.1.0 release. Please look at creating a real ESPHome component and “importing” it into your configuration with [External Components](https://esphome.io/components/external_components).

You can find some basic documentation on creating your own components at [Contributing to ESPHome](https://esphome.io/guides/contributing#contributing-to-esphome).

**Comment by dbuezas** [comment]
Someone made an external component (search the issues), but if i recall correctly it was a bit more limited.
I may eventually give it try but don't expect it soon

**Comment by Virusmater** [comment]
If somebody else is suffering from the custom platform removal - I was able to make it work with the following custom component
```
substitutions:
  name: esphome-web-2fd588
  friendly_name: SubGZ

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false

esp32:
  board: denky32
  framework:
    type: esp-idf

external_components:
  - source: github://swoboda1337/components-esphome@main
    components: [ cc1101 ]

ota:
  platform: esphome
  id: my_ota
  password: !secret ota_password

# Enable Home Assistant API
api:

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:

logger:
  level: DEBUG

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

cc1101:
  id: transceiver
  cs_pin: GPIO5
  bandwidth: 200
  frequency: 433920

remote_transmitter:
  pin: GPIO12  # GDO0
  carrier_duty_percent: 100%

remote_receiver:
  pin: GPIO27  # GDO2
  dump:
    - raw



button:
  - platform: template
    name: Fan off
    on_press:
      - cc1101.begin_tx: transceiver
      - remote_transmitter.transmit_raw:
          # prettier-ignore
          code: [1638, -131, 4732, -1450, 769, -345, 380, -713, 719, -362, 762, -348, 368, -721, 386, -753, 368, -721, 711, -369, 369, -749, 736, -345, 365, -722, 385, -753, 368, -720, 362, -704, 770, -363, 361, -724, 372, -716, 397, -724, 722, -361, 375,  -744, 371, -715, 374, -719, 364, -764, 728, -344, 729, -356, 370, -767, 714, -361, 725, -371, 364, -759, 353, -719, 364, -740, 746, -367, 365, -716, 374, -719, 764, -362, 730, -344, 728, -407, 728, -344, 364, -739, 371, -9124, 4788, -1467, 744, -379, 360, -730, 719, -362, 754, -370, 344, -739, 352, -720, 414, -707, 725, -370, 364, -713, 770, -368, 364, -715, 373, -743, 364, -740, 352, -719, 754, -362, 376, -718, 363, -739, 343, -772, 715, -374, 367, -720, 360, -754, 369, -719, 360, -731, 744, -378, 710, -369, 366, -749, 739, -347, 743, -339, 386, -754, 368, -720, 361, -729, 745, -363, 361, -726, 371, -715, 775, -343, 722, -361, 727, -370, 765, -362, 353, -720, 379, -9135, 4802, -1443, 731, -394, 344, -739, 730, -343, 729, -408, 353, -719, 365, -734, 372, -744, 722, -361, 376, -718, 765, -359, 373, -718, 363, -711, 393, -743, 363, -711, 744, -351, 387, -737, 368, -720, 361, -753, 719, -362, 362, -725, 364]
      - cc1101.end_tx: transceiver


  - platform: template
    name: Fan new2
    on_press:
      - cc1101.begin_tx: transceiver
      - remote_transmitter.transmit_raw:
          # prettier-ignore
          code: [1612, -146, 253]
      - remote_transmitter.transmit_raw:
          # prettier-ignore
          code: [290, -2742, 292, -280, 267, -1393, 271, -259, 291, -1350, 293, -1383, 260, -267, 289, -264, 267, -1377, 275, -285, 267, -1378, 276, -1385, 259, -311, 250, -1387, 280, -261, 287, -259, 261, -1391, 259, -1376, 270, -303, 259, -300, 261, -1376, 285, -250, 300, -1351, 287, -272, 274, -1359, 287, -1376, 284, -268, 284, -279, 269, -1389, 258, -261, 300, -1332, 319, -262, 250, -1395, 296, -262, 274, -1373, 272, -287, 272, -1375, 273, -262, 303, -1373, 272, -262, 279, -1346, 317, -262, 259, -1374, 269, -302, 258, -1375, 269, -302, 276, -1367, 270, -257, 306, -1344, 293, -283, 260, -1372, 269, -300, 259, -1374, 269, -301, 259, -1375, 269, -277, 287, -1347, 292, -278, 262, -1372, 316, -1331, 294, -286, 251, -293, 267, -1391, 269, -255, 312, -1374, 245]
      - remote_transmitter.transmit_raw:
          # prettier-ignore
          code: [290, -2747, 258, -310, 250, -1388, 279, -240, 315, -1335, 299, -1365, 286, -268, 273, -284, 267, -1381, 279, -287, 271, -1360, 274, -1391, 259, -261, 298, -1384, 279, -235, 314, -256, 266, -1390, 245, -1381, 276, -285, 267, -277, 290, -1372, 295, -236, 314, -1351, 292, -259, 267]
      - cc1101.end_tx: transceiver
```
